plugins {
 id 'com.android.application'
 id 'org.jetbrains.kotlin.android' version '1.9.22'
 id 'com.google.gms.google-services'
}
android {
 namespace 'com.jbchat.app'
 compileSdk 34
 defaultConfig {
  applicationId "com.jbchat.app"
  minSdk 24
  targetSdk 34
  versionCode 1
  versionName "1.0"
 }
 buildTypes { release { minifyEnabled false } }
 buildFeatures { compose true }
 composeOptions { kotlinCompilerExtensionVersion '1.5.8' }
}
dependencies {
 implementation platform('com.google.firebase:firebase-bom:32.8.1')
 implementation 'com.google.firebase:firebase-firestore-ktx'
 implementation 'com.google.firebase:firebase-messaging-ktx'
 implementation 'androidx.activity:activity-compose:1.8.2'
 implementation 'androidx.compose.material3:material3:1.2.1'
}
